sudo: required

services:
  - docker

env:
  global:
    - CGO_ENABLED=0
    - GOOS=linux

language: go

go:
  - 1.7.x
  #- master 

before_install:
  - go get -v ./...

install:
  # build our Go application
  #- go build 
  - time go build -a -tags netgo -ldflags '-w' -o main main.go

before_script:
  # build Docker image with compiled code, lauch side containers for testings
  #- ls -l $HOME/gopath/bin
  - ls -l
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - time docker build -t go-docker-test1 -f Dockerfile .
  - docker images
  - docker run -d -p 8080:8080 go-docker-test1

script:
  - echo 'MARK: Launch integration tests'
  - curl http://localhost:8080/stats


after_success:
# deploy artifacts, etc
  - echo 'MARK: Deploy artifacts to somewhere'
