sudo: required

services:
  - docker

env:
  global:
    - GOOS=linux

language: go

go:
  - 1.7.x

before_install:
  - go get -v ./...

install:
  # build our Go application
  #- go build
  - time go build -v --ldflags '-extldflags "-static"' -o main

before_script:
  # build Docker image with compiled code, lauch side containers for testings
  #- ls -l $HOME/gopath/bin
  - ls -l
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - time docker build -t go-docker-test1 -f Dockerfile_alpine .
  - docker images
  - docker run -d -p 8080:8080 go-docker-test1

script:
  - curl http://localhost:8080/stats


after_success:
  # deploy artifacts, etc
  - docker tag go-docker-test1 skandyla/go-docker-test1:latest
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push skandyla/go-docker-test1:latest


#deploy:
#    provider: bintray
#    file: "Path to a descriptor file, containing information for the Bintray upload"
#    user: "Bintray user"
#    key: "Bintray API key"
#    passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
#    dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"
