sudo: required

services:
  - docker

env:
  global:
    - CGO_ENABLED=0
    - GOOS=linux

language: go

go:
  - 1.7.x
  #- master 

before_install:
  - go get -v ./...

install:
  - go build 
  - go build -a -tags netgo -ldflags '-w' -o main main.go

script:
  - ls -l $HOME/gopath/bin
  - ls -l
  - time docker build -t go-docker-test1 -f Dockerfile .
  - docker images
  - docker ps -a
  - ls -l

