sudo: required

services:
  - docker

env:
  global:
    - CGO_ENABLED=0
    - GOOS=linux

language: go

go:
  - 1.7.x
  - master 
gobuild_args: -a -tags netgo -ldflags '-w'

before_install:
  - go get -v ./...

install:
  - go build

#script:
# - go test ./...

